apiVersion: v1
kind: Pod
metadata:
  name: flower-pod
  namespace: elzabeth-ns
  labels:
    app: flower
spec:
  containers:
    - name: flower-container
      image: elzabeth03/flowerapp:v1.1.0
      ports:
        - containerPort: 3015